### ISSUE TITLE
"Segmentation fault (core dumped)" when denoising the image

### ISSUE THREAD

**Issue by transiteration** [hi-paris/merlin#23]
When I am trying to denoise this SAR [image](https://drive.google.com/file/d/1YBqMMnKyDM7JhKYJlxb6WHMnqmpYR3x7/view?usp=drive_link) I facing error "Segmentation fault (core dumped)". 

```
from deepdespeckling.utils.load_cosar import load_tiff_image
from deepdespeckling.utils.constants import PATCH_SIZE, STRIDE_SIZE
from deepdespeckling.sar2sar.sar2sar_denoiser import Sar2SarDenoiser

image_path="images/image_sample.tiff"
model_weights_path = "models/sar2sar.pth"

image = load_tiff_image(image_path)

denoiser = Sar2SarDenoiser()
denoised_image = denoiser.denoise_image(
                image, model_weights_path, patch_size=PATCH_SIZE, stride_size=STRIDE_SIZE)

```

I think the problem is in deepdespeckling/sar2sar/sar2sar_denoiser.py with function `def denoise_image_kernel(...)`
Please, I appreciate any help

**Comment by brash6** [comment]
Hello, your image link seems to be broken, can you provide a working one ?
